#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $REZOR_REPO == "rezorbot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $REZOR_REPO == "REZORBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $REZOR_REPO =~ $regex ]]
    then
        if [[ $REZOR_REPO_BRANCH ]]
        then
            echo "${REZOR_REPO}/archive/${REZOR_REPO_BRANCH}.zip"
        else
            echo "${REZOR_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0gxTTRONUhVMFAvTUFGSUEtVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="mafiabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    REZORPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $REZORPATH
    echo "    Starting MafiaBot    "
    echo "
                          ╔--══╦══╦══╦══╦══╦
                          ║║║║║╔╗║═╦╩║║╣╔╗║
                          ║║║║║╠╣║╔╝╔║║╣╠╣║
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot